### ISSUE TITLE
UX: provide LED status colors access

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/trussed#5]
We need to indicate in UX a global and permanent failure status to the user (with an infinite red LED blinking animation).
Specifically 10s-green-blinking-LED and infinite-red-blinking-LED, both animations with the highest priority.

Ideas: 
* extend trussed api with something like "SetStatus"
* extend UI Status enum with "Success" (green-blink)
* reuse "Error" from UI Status enum
* introduce specialized `client::error()` and `client::success()` api-wrapper functions to be available for clients

Any "ui::Status" extension will likely break backwards-compatibility, we should choose how to break it...

cc @jans23 @daringer

**Comment by szszszsz** [comment]
Additional requirements:
1. Error flag should be persistent over power cycles
2. It should be clearable after providing PIN to the Secrets App

**Comment by daringer** [comment]
introduce `Custom(u8)` state in Trussed
